***R (programming language)***

******
*calculator*
```{r}
5  +  49 
3  *  5 
3  -  8 
12 / 4 
```
------
*the sequence of integers*
```{r}
options(width=20)#寬度
1:20
```
------
*mean*
```{r}
x=10:31
mean(x)
```

*variance*
```{r}
x=10:31
var(x)
```

------
*combine numbers in to a vector*
```{r}
x=c(0,10,20)
x
```

------
*concatenate*
```{r}
x=c(0,10,20)
number10to20=10:20
c(number10to20,x)
```

------
*extracting elements from vectors*
```{r}
number10to20=10:20
number10to20[5]
```


------
*repeat(x,times)*
```{r}
rep(3, 12)# repeat the value 3, 12 times
rep(seq(2, 20, by=2), 2)# repeat the pattern 2 4 ... 20, 2 times
rep(c(1, 4), c(3, 2))# repeat 1, 3 times and 4, 2 times
rep(c(1, 4), each=3)# repeat each value 3 times
rep(seq(2, 20, 2), rep(2, 10))# repeat each value 2 times
```

------
*combine strings in to a vector*
```{r}
colors=c("red", "yellow", "blue")
colors
more.colors=c(colors, "green", "magenta", "cyan")
more.colors

```
------
*substr(x, start, stop)*
```{r}
substr(colors,2,3)
```
------
*paste(x,"what we want to paste on x",sep="what we use to seperate by")*
```{r}
paste(colors, "flowers")
paste0(colors, "flowers")#paste without being seperate by space
paste(colors, "flowers",sep=":")
```

------
*matrix*
```{r}
m=matrix(1:6, nrow=2, ncol=3) #by column
m
m2=matrix(1:6, nrow=2, ncol=3,byrow=T) #by row
m2
```
------
*array(m,n,x):make a matrix into x(number) matrixs*
```{r}
array(1:60,c(5,3,4))#four 5*3 matrixs
```

```{r}
array(1:120,c(5,3,4,2))#eight 5*3 matrixs
```

------
*data.frame():construct data frames from vectors*
```{r}
colors=c("red", "yellow", "blue")
numbers=c(1, 2, 3)
colors.and.numbers=data.frame(colors, numbers,
                              more.numbers=c(4, 5, 6))
colors.and.numbers
```

------
*histogram*
```{r}
x <- c(12, 15, 13, 20, 14, 16, 10, 10, 8, 15)
hist(x)
```

------
*scatterplot*
```{r}
x =seq(1, 10)
y = x^2 - 10*x
plot(x, y)

```




